window.__AHA_LOCAL_SEED__ = window.__AHA_LOCAL_SEED__ || {
  "inventoryTransactions": [
    {
      "id": "inv-import-kho-103-nhap-106",
      "itemName": "MÁY MẮT",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 1,
      "note": "P5",
      "date": "2026-01-31",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2026-01-31T08:01:46",
      "timestamp": "2026-01-31T08:01:46"
    },
    {
      "id": "inv-import-kho-102-xuat-105",
      "itemName": "BĂNG VỆ SINH",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "Sunny lấy thùng có 2 hộp dở (1hộp 30M dở, 1 hộp 16m)",
      "date": "2026-01-21",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2026-01-21T08:01:45",
      "timestamp": "2026-01-21T08:01:45"
    },
    {
      "id": "inv-import-kho-101-xuat-104",
      "itemName": "MÁY THỔI  VITALITY WAND",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "Cô Dung",
      "date": "2026-01-21",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2026-01-21T08:01:44",
      "timestamp": "2026-01-21T08:01:44"
    },
    {
      "id": "inv-import-kho-100-xuat-103",
      "itemName": "TERA P90 Plus",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "Cô Dung",
      "date": "2026-01-21",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2026-01-21T08:01:43",
      "timestamp": "2026-01-21T08:01:43"
    },
    {
      "id": "inv-import-spa-44-nhap-150",
      "itemName": "GEL XANH",
      "area": "SPA",
      "type": "NHAP",
      "quantity": 1,
      "note": "DỊCH VỤ SPA",
      "date": "2026-01-13",
      "transferId": "invtf-import-0020",
      "transferRole": "IN",
      "transferCounterpartyArea": "KHO",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2026-01-13T08:02:30",
      "timestamp": "2026-01-13T08:02:30"
    },
    {
      "id": "inv-import-kho-99-xuat-102",
      "itemName": "BVS NGÀY 16M",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 3,
      "note": "Miu ck",
      "date": "2026-01-12",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2026-01-12T08:01:42",
      "timestamp": "2026-01-12T08:01:42"
    },
    {
      "id": "inv-import-spa-45-xuat-151",
      "itemName": "MÁY BT10",
      "area": "SPA",
      "type": "XUAT",
      "quantity": 1,
      "note": "Kiệt mang sang ba",
      "date": "2026-01-11",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2026-01-11T08:02:31",
      "timestamp": "2026-01-11T08:02:31"
    },
    {
      "id": "inv-import-kho-98-xuat-101",
      "itemName": "BVS HÀNG NGÀY 30M",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 5,
      "note": "Miu ck 100k",
      "date": "2026-01-11",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2026-01-11T08:01:41",
      "timestamp": "2026-01-11T08:01:41"
    },
    {
      "id": "inv-import-spa-36-nhap-142",
      "itemName": "MÁY THỔI  VITALITY WAND",
      "area": "SPA",
      "type": "NHAP",
      "quantity": 1,
      "note": "DỊCH VỤ SPA",
      "date": "2026-01-10",
      "transferId": "invtf-import-0001",
      "transferRole": "IN",
      "transferCounterpartyArea": "KHO",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2026-01-10T08:02:22",
      "timestamp": "2026-01-10T08:02:22"
    },
    {
      "id": "inv-import-kho-97-xuat-100",
      "itemName": "MÁY THỔI  VITALITY WAND",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "Dùng spa HF020250500264E",
      "date": "2026-01-10",
      "transferId": "invtf-import-0001",
      "transferRole": "OUT",
      "transferCounterpartyArea": "SPA",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2026-01-10T08:01:40",
      "timestamp": "2026-01-10T08:01:40"
    },
    {
      "id": "inv-import-kho-96-nhap-99",
      "itemName": "MÁY THỔI  VITALITY WAND",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 2,
      "note": "C Dung trả HF020250500264E, HF020250500263E",
      "date": "2026-01-10",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2026-01-10T08:01:39",
      "timestamp": "2026-01-10T08:01:39"
    },
    {
      "id": "inv-import-kho-95-nhap-98",
      "itemName": "Máy nâng cơ P90+",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 1,
      "note": "trả đầu còn thiếu hội thảo 15/10",
      "date": "2026-01-05",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2026-01-05T08:01:38",
      "timestamp": "2026-01-05T08:01:38"
    },
    {
      "id": "inv-import-kho-94-xuat-97",
      "itemName": "GEL NÂU",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "chuyển ra HN",
      "date": "2026-01-04",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2026-01-04T08:01:37",
      "timestamp": "2026-01-04T08:01:37"
    },
    {
      "id": "inv-import-kho-93-xuat-96",
      "itemName": "GEL XANH",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "chuyển ra HN",
      "date": "2026-01-04",
      "transferId": "invtf-import-0020",
      "transferRole": "OUT",
      "transferCounterpartyArea": "SPA",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2026-01-04T08:01:36",
      "timestamp": "2026-01-04T08:01:36"
    },
    {
      "id": "inv-import-kho-92-xuat-95",
      "itemName": "TERA P90 Plus",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "chuyển ra HN P90P205200085",
      "date": "2026-01-04",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2026-01-04T08:01:35",
      "timestamp": "2026-01-04T08:01:35"
    },
    {
      "id": "inv-import-kho-91-xuat-94",
      "itemName": "BỘ PHỤ KIỆN MÁY BT10",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "chuyển ra HN",
      "date": "2026-01-04",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2026-01-04T08:01:34",
      "timestamp": "2026-01-04T08:01:34"
    },
    {
      "id": "inv-import-kho-90-xuat-93",
      "itemName": "MÁY BT10",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "chuyển ra HN",
      "date": "2026-01-04",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2026-01-04T08:01:33",
      "timestamp": "2026-01-04T08:01:33"
    },
    {
      "id": "inv-import-kho-89-xuat-92",
      "itemName": "MÁY THỔI  VITALITY WAND",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "chuyển ra HN HF020250500265E",
      "date": "2026-01-04",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2026-01-04T08:01:32",
      "timestamp": "2026-01-04T08:01:32"
    },
    {
      "id": "inv-import-kho-88-nhap-91",
      "itemName": "MÁY THỔI  VITALITY WAND",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 2,
      "note": "kho",
      "date": "2026-01-02",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2026-01-02T08:01:31",
      "timestamp": "2026-01-02T08:01:31"
    },
    {
      "id": "inv-import-kho-87-xuat-90",
      "itemName": "MÁY BT10",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "Tuấn",
      "date": "2025-12-28",
      "transferId": "invtf-import-0022",
      "transferRole": "OUT",
      "transferCounterpartyArea": "SPA",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-12-28T08:01:30",
      "timestamp": "2025-12-28T08:01:30"
    },
    {
      "id": "inv-import-spa-22-nhap-127",
      "itemName": "GEL XANH",
      "area": "SPA",
      "type": "NHAP",
      "quantity": 1,
      "note": "DỊCH VỤ SPA",
      "date": "2025-12-23",
      "transferId": "invtf-import-0002",
      "transferRole": "IN",
      "transferCounterpartyArea": "KHO",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-12-23T08:02:07",
      "timestamp": "2025-12-23T08:02:07"
    },
    {
      "id": "inv-import-kho-86-nhap-89",
      "itemName": "MÁY THỔI  VITALITY WAND",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 1,
      "note": "chú Huế đưa đi bảo hành",
      "date": "2025-12-23",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-12-23T08:01:29",
      "timestamp": "2025-12-23T08:01:29"
    },
    {
      "id": "inv-import-kho-85-xuat-88",
      "itemName": "MÁY THỔI  VITALITY WAND",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "đưa chú Huế (đổi máy của chú Huế để đi bảo hành)",
      "date": "2025-12-23",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-12-23T08:01:28",
      "timestamp": "2025-12-23T08:01:28"
    },
    {
      "id": "inv-import-kho-84-xuat-87",
      "itemName": "GEL XANH",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "xuất dùng spa",
      "date": "2025-12-23",
      "transferId": "invtf-import-0002",
      "transferRole": "OUT",
      "transferCounterpartyArea": "SPA",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-12-23T08:01:27",
      "timestamp": "2025-12-23T08:01:27"
    },
    {
      "id": "inv-import-kho-83-xuat-86",
      "itemName": "BVS HÀNG NGÀY 30M",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 2,
      "note": "Sunny lấy",
      "date": "2025-12-23",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-12-23T08:01:26",
      "timestamp": "2025-12-23T08:01:26"
    },
    {
      "id": "inv-import-kho-82-xuat-85",
      "itemName": "BVS HÀNG NGÀY 30M",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 5,
      "note": "Mia ck 100k",
      "date": "2025-12-23",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-12-23T08:01:25",
      "timestamp": "2025-12-23T08:01:25"
    },
    {
      "id": "inv-import-kho-81-xuat-84",
      "itemName": "BVS ĐÊM 15M",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 15,
      "note": "đưa chị Hiếu (da) Sunny tính",
      "date": "2025-12-23",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-12-23T08:01:24",
      "timestamp": "2025-12-23T08:01:24"
    },
    {
      "id": "inv-import-spa-26-nhap-132",
      "itemName": "MÁY BT10",
      "area": "SPA",
      "type": "NHAP",
      "quantity": 1,
      "note": "DỊCH VỤ SPA",
      "date": "2025-12-09",
      "transferId": "invtf-import-0021",
      "transferRole": "IN",
      "transferCounterpartyArea": "KHO",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-12-09T08:02:12",
      "timestamp": "2025-12-09T08:02:12"
    },
    {
      "id": "inv-import-kho-80-nhap-83",
      "itemName": "TERA P90 Plus",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 1,
      "note": "chú Vĩ trả, dùng spa",
      "date": "2025-12-09",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-12-09T08:01:23",
      "timestamp": "2025-12-09T08:01:23"
    },
    {
      "id": "inv-import-kho-78-xuat-82",
      "itemName": "MÁY BT10",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 2,
      "note": "DỊCH VỤ SPA",
      "date": "2025-12-09",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-12-09T08:01:22",
      "timestamp": "2025-12-09T08:01:22"
    },
    {
      "id": "inv-import-spa-25-xuat-131",
      "itemName": "MÁY BT10",
      "area": "SPA",
      "type": "XUAT",
      "quantity": 1,
      "note": "7 tặng 1, xuất 2 sử dụng p6 1, Sunny lấy 1",
      "date": "2025-12-06",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-12-06T08:02:11",
      "timestamp": "2025-12-06T08:02:11"
    },
    {
      "id": "inv-import-spa-25-nhap-130",
      "itemName": "MÁY BT10",
      "area": "SPA",
      "type": "NHAP",
      "quantity": 1,
      "note": "7 tặng 1, xuất 2 sử dụng p6 1, Sunny lấy 1",
      "date": "2025-12-06",
      "transferId": "invtf-import-0022",
      "transferRole": "IN",
      "transferCounterpartyArea": "KHO",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-12-06T08:02:10",
      "timestamp": "2025-12-06T08:02:10"
    },
    {
      "id": "inv-import-kho-77-xuat-81",
      "itemName": "MÁY BT10",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 2,
      "note": "7 tặng 1, suất 2 sử dụng p6 1, Sunny lấy 1",
      "date": "2025-12-06",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-12-06T08:01:21",
      "timestamp": "2025-12-06T08:01:21"
    },
    {
      "id": "inv-import-kho-77-nhap-80",
      "itemName": "MÁY BT10",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 8,
      "note": "7 tặng 1, suất 2 sử dụng p6 1, Sunny lấy 1",
      "date": "2025-12-06",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-12-06T08:01:20",
      "timestamp": "2025-12-06T08:01:20"
    },
    {
      "id": "inv-import-spa-43-nhap-149",
      "itemName": "TERA P90 Plus",
      "area": "SPA",
      "type": "NHAP",
      "quantity": 1,
      "note": "DỊCH VỤ SPA",
      "date": "2025-12-02",
      "transferId": "invtf-import-0003",
      "transferRole": "IN",
      "transferCounterpartyArea": "KHO",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-12-02T08:02:29",
      "timestamp": "2025-12-02T08:02:29"
    },
    {
      "id": "inv-import-spa-35-xuat-141",
      "itemName": "MÁY THỔI  VITALITY WAND",
      "area": "SPA",
      "type": "XUAT",
      "quantity": 1,
      "note": "đưa lên ba Sunny",
      "date": "2025-12-02",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-12-02T08:02:21",
      "timestamp": "2025-12-02T08:02:21"
    },
    {
      "id": "inv-import-spa-34-xuat-140",
      "itemName": "MÁY THỔI  VITALITY WAND",
      "area": "SPA",
      "type": "XUAT",
      "quantity": 1,
      "note": "CHÚ HUẾ MUA",
      "date": "2025-12-02",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-12-02T08:02:20",
      "timestamp": "2025-12-02T08:02:20"
    },
    {
      "id": "inv-import-spa-24-xuat-129",
      "itemName": "MÁY BT10",
      "area": "SPA",
      "type": "XUAT",
      "quantity": 1,
      "note": "TẶNG CHÚ HUẾ",
      "date": "2025-12-02",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-12-02T08:02:09",
      "timestamp": "2025-12-02T08:02:09"
    },
    {
      "id": "inv-import-spa-19-nhap-124",
      "itemName": "GEL NÂU",
      "area": "SPA",
      "type": "NHAP",
      "quantity": 1,
      "note": "DỊCH VỤ SPA",
      "date": "2025-12-02",
      "transferId": "invtf-import-0004",
      "transferRole": "IN",
      "transferCounterpartyArea": "KHO",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-12-02T08:02:04",
      "timestamp": "2025-12-02T08:02:04"
    },
    {
      "id": "inv-import-spa-4-xuat-108",
      "itemName": "BỘ PHỤ KIỆN MÁY BT10",
      "area": "SPA",
      "type": "XUAT",
      "quantity": 1,
      "note": "CHÚ HUẾ MUA",
      "date": "2025-12-02",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-12-02T08:01:48",
      "timestamp": "2025-12-02T08:01:48"
    },
    {
      "id": "inv-import-kho-76-xuat-79",
      "itemName": "TERA P90 Plus",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "DỊCH VỤ SPA",
      "date": "2025-12-02",
      "transferId": "invtf-import-0003",
      "transferRole": "OUT",
      "transferCounterpartyArea": "SPA",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-12-02T08:01:19",
      "timestamp": "2025-12-02T08:01:19"
    },
    {
      "id": "inv-import-kho-75-xuat-78",
      "itemName": "MÁY THỔI  VITALITY WAND",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "DỊCH VỤ SPA",
      "date": "2025-12-02",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-12-02T08:01:18",
      "timestamp": "2025-12-02T08:01:18"
    },
    {
      "id": "inv-import-kho-74-xuat-77",
      "itemName": "MÁY THỔI  VITALITY WAND",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "CHÚ HUẾ MUA",
      "date": "2025-12-02",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-12-02T08:01:17",
      "timestamp": "2025-12-02T08:01:17"
    },
    {
      "id": "inv-import-kho-73-xuat-76",
      "itemName": "MÁY BT10",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "TẶNG CHÚ HUẾ",
      "date": "2025-12-02",
      "transferId": "invtf-import-0021",
      "transferRole": "OUT",
      "transferCounterpartyArea": "SPA",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-12-02T08:01:16",
      "timestamp": "2025-12-02T08:01:16"
    },
    {
      "id": "inv-import-kho-72-xuat-75",
      "itemName": "GEL NÂU",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "DỊCH VỤ SPA",
      "date": "2025-12-02",
      "transferId": "invtf-import-0004",
      "transferRole": "OUT",
      "transferCounterpartyArea": "SPA",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-12-02T08:01:15",
      "timestamp": "2025-12-02T08:01:15"
    },
    {
      "id": "inv-import-kho-71-xuat-74",
      "itemName": "BỘ PHỤ KIỆN MÁY BT10",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "CHÚ HUẾ MUA",
      "date": "2025-12-02",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-12-02T08:01:14",
      "timestamp": "2025-12-02T08:01:14"
    },
    {
      "id": "inv-import-spa-27-nhap-133",
      "itemName": "MÁY LỌC KHÔNG KHÍ",
      "area": "SPA",
      "type": "NHAP",
      "quantity": 1,
      "note": "P2",
      "date": "2025-12-01",
      "transferId": "invtf-import-0005",
      "transferRole": "IN",
      "transferCounterpartyArea": "KHO",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-12-01T08:02:13",
      "timestamp": "2025-12-01T08:02:13"
    },
    {
      "id": "inv-import-kho-70-nhap-73",
      "itemName": "TĂNG CƯỜNG SINH LỰC",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 13,
      "note": "",
      "date": "2025-12-01",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-12-01T08:01:13",
      "timestamp": "2025-12-01T08:01:13"
    },
    {
      "id": "inv-import-kho-69-nhap-72",
      "itemName": "NƯỚC GIẢI ĐỘC GAN",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 3,
      "note": "",
      "date": "2025-12-01",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-12-01T08:01:12",
      "timestamp": "2025-12-01T08:01:12"
    },
    {
      "id": "inv-import-kho-68-xuat-71",
      "itemName": "MÁY LỌC KHÔNG KHÍ",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "P6",
      "date": "2025-12-01",
      "transferId": "invtf-import-0005",
      "transferRole": "OUT",
      "transferCounterpartyArea": "SPA",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-12-01T08:01:11",
      "timestamp": "2025-12-01T08:01:11"
    },
    {
      "id": "inv-import-kho-68-nhap-70",
      "itemName": "MÁY LỌC KHÔNG KHÍ",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 2,
      "note": "P6",
      "date": "2025-12-01",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-12-01T08:01:10",
      "timestamp": "2025-12-01T08:01:10"
    },
    {
      "id": "inv-import-kho-67-nhap-69",
      "itemName": "LÕI LỌC MÁY H+",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 10,
      "note": "",
      "date": "2025-12-01",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-12-01T08:01:09",
      "timestamp": "2025-12-01T08:01:09"
    },
    {
      "id": "inv-import-spa-39-xuat-145",
      "itemName": "SÁP GIỮ ẤM C3",
      "area": "SPA",
      "type": "XUAT",
      "quantity": 1,
      "note": "Cô Như",
      "date": "2025-11-28",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-28T08:02:25",
      "timestamp": "2025-11-28T08:02:25"
    },
    {
      "id": "inv-import-spa-37-xuat-143",
      "itemName": "SÁP GIỮ ẤM  C4",
      "area": "SPA",
      "type": "XUAT",
      "quantity": 1,
      "note": "Cô Như",
      "date": "2025-11-28",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-28T08:02:23",
      "timestamp": "2025-11-28T08:02:23"
    },
    {
      "id": "inv-import-spa-17-xuat-122",
      "itemName": "DẦU HOA 311",
      "area": "SPA",
      "type": "XUAT",
      "quantity": 1,
      "note": "Cô Như",
      "date": "2025-11-28",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-28T08:02:02",
      "timestamp": "2025-11-28T08:02:02"
    },
    {
      "id": "inv-import-spa-13-xuat-117",
      "itemName": "DẦU HOA 202",
      "area": "SPA",
      "type": "XUAT",
      "quantity": 1,
      "note": "Cô Như",
      "date": "2025-11-28",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-28T08:01:57",
      "timestamp": "2025-11-28T08:01:57"
    },
    {
      "id": "inv-import-spa-9-xuat-113",
      "itemName": "DẦU GỘI THẢO DƯỢC",
      "area": "SPA",
      "type": "XUAT",
      "quantity": 2,
      "note": "Cô Như",
      "date": "2025-11-28",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-28T08:01:53",
      "timestamp": "2025-11-28T08:01:53"
    },
    {
      "id": "inv-import-kho-65-xuat-68",
      "itemName": "SÁP GIỮ ẤM C3",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "Cô Như",
      "date": "2025-11-28",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-28T08:01:08",
      "timestamp": "2025-11-28T08:01:08"
    },
    {
      "id": "inv-import-kho-64-xuat-67",
      "itemName": "SÁP GIỮ ẤM  C4",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "Cô Như",
      "date": "2025-11-28",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-28T08:01:07",
      "timestamp": "2025-11-28T08:01:07"
    },
    {
      "id": "inv-import-kho-60-xuat-66",
      "itemName": "DẦU HOA 311",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "Cô Như",
      "date": "2025-11-28",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-28T08:01:06",
      "timestamp": "2025-11-28T08:01:06"
    },
    {
      "id": "inv-import-kho-59-xuat-65",
      "itemName": "DẦU HOA 202",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "Cô Như",
      "date": "2025-11-28",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-28T08:01:05",
      "timestamp": "2025-11-28T08:01:05"
    },
    {
      "id": "inv-import-kho-58-xuat-64",
      "itemName": "DẦU GỘI THẢO DƯỢC",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 2,
      "note": "Cô Như",
      "date": "2025-11-28",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-28T08:01:04",
      "timestamp": "2025-11-28T08:01:04"
    },
    {
      "id": "inv-import-spa-29-xuat-135",
      "itemName": "MÁY MẮT",
      "area": "SPA",
      "type": "XUAT",
      "quantity": 1,
      "note": "ANH NGỌC ANH",
      "date": "2025-11-26",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-26T08:02:15",
      "timestamp": "2025-11-26T08:02:15"
    },
    {
      "id": "inv-import-spa-5-xuat-109",
      "itemName": "BVS HÀNG NGÀY 30M",
      "area": "SPA",
      "type": "XUAT",
      "quantity": 1,
      "note": "C ÁNH",
      "date": "2025-11-26",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-26T08:01:49",
      "timestamp": "2025-11-26T08:01:49"
    },
    {
      "id": "inv-import-kho-57-xuat-63",
      "itemName": "MÁY MẮT",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "ANH NGỌC ANH",
      "date": "2025-11-26",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-26T08:01:03",
      "timestamp": "2025-11-26T08:01:03"
    },
    {
      "id": "inv-import-kho-56-xuat-62",
      "itemName": "BVS HÀNG NGÀY 30M",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 30,
      "note": "C ÁNH",
      "date": "2025-11-26",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-26T08:01:02",
      "timestamp": "2025-11-26T08:01:02"
    },
    {
      "id": "inv-import-spa-23-nhap-128",
      "itemName": "MÁY BT10",
      "area": "SPA",
      "type": "NHAP",
      "quantity": 1,
      "note": "DỊCH VỤ SPA",
      "date": "2025-11-25",
      "transferId": "invtf-import-0006",
      "transferRole": "IN",
      "transferCounterpartyArea": "KHO",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-25T08:02:08",
      "timestamp": "2025-11-25T08:02:08"
    },
    {
      "id": "inv-import-kho-55-xuat-61",
      "itemName": "MÁY BT10",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "DỊCH VỤ SPA",
      "date": "2025-11-25",
      "transferId": "invtf-import-0006",
      "transferRole": "OUT",
      "transferCounterpartyArea": "SPA",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-25T08:01:01",
      "timestamp": "2025-11-25T08:01:01"
    },
    {
      "id": "inv-import-spa-21-nhap-126",
      "itemName": "GEL XANH",
      "area": "SPA",
      "type": "NHAP",
      "quantity": 1,
      "note": "DỊCH VỤ SPA",
      "date": "2025-11-24",
      "transferId": "invtf-import-0007",
      "transferRole": "IN",
      "transferCounterpartyArea": "KHO",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-24T08:02:06",
      "timestamp": "2025-11-24T08:02:06"
    },
    {
      "id": "inv-import-kho-54-nhap-60",
      "itemName": "MÁY BT10",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 3,
      "note": "",
      "date": "2025-11-24",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-24T08:01:00",
      "timestamp": "2025-11-24T08:01:00"
    },
    {
      "id": "inv-import-kho-53-xuat-59",
      "itemName": "GEL XANH",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "DỊCH VỤ SPA",
      "date": "2025-11-24",
      "transferId": "invtf-import-0007",
      "transferRole": "OUT",
      "transferCounterpartyArea": "SPA",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-24T08:00:59",
      "timestamp": "2025-11-24T08:00:59"
    },
    {
      "id": "inv-import-kho-52-nhap-58",
      "itemName": "BỘ PHỤ KIỆN MÁY BT10",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 7,
      "note": "",
      "date": "2025-11-24",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-24T08:00:58",
      "timestamp": "2025-11-24T08:00:58"
    },
    {
      "id": "inv-import-spa-33-xuat-139",
      "itemName": "MÁY THỔI  VITALITY WAND",
      "area": "SPA",
      "type": "XUAT",
      "quantity": 1,
      "note": "ĐƯA C DUNG ĐỂ BẢO HÀNH ĐỔI TRẢ Seri HF02050400243E",
      "date": "2025-11-22",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-22T08:02:19",
      "timestamp": "2025-11-22T08:02:19"
    },
    {
      "id": "inv-import-kho-51-xuat-57",
      "itemName": "MÁY THỔI  VITALITY WAND",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "ĐƯA C DUNG ĐỂ BẢO HÀNH ĐỔI TRẢ Seri HF02050400243E",
      "date": "2025-11-22",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-22T08:00:57",
      "timestamp": "2025-11-22T08:00:57"
    },
    {
      "id": "inv-import-kho-50-nhap-56",
      "itemName": "SÁP GIỮ ẤM C3",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 1,
      "note": "",
      "date": "2025-11-16",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-16T08:00:56",
      "timestamp": "2025-11-16T08:00:56"
    },
    {
      "id": "inv-import-kho-49-nhap-55",
      "itemName": "MÁY MẮT",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 1,
      "note": "",
      "date": "2025-11-16",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-16T08:00:55",
      "timestamp": "2025-11-16T08:00:55"
    },
    {
      "id": "inv-import-kho-48-nhap-54",
      "itemName": "DẦU HOA 311",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 2,
      "note": "",
      "date": "2025-11-16",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-16T08:00:54",
      "timestamp": "2025-11-16T08:00:54"
    },
    {
      "id": "inv-import-kho-47-nhap-53",
      "itemName": "DẦU HOA 202",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 8,
      "note": "",
      "date": "2025-11-16",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-16T08:00:53",
      "timestamp": "2025-11-16T08:00:53"
    },
    {
      "id": "inv-import-kho-46-nhap-52",
      "itemName": "DẦU GỘI THẢO DƯỢC",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 2,
      "note": "",
      "date": "2025-11-16",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-16T08:00:52",
      "timestamp": "2025-11-16T08:00:52"
    },
    {
      "id": "inv-import-spa-16-xuat-121",
      "itemName": "DẦU HOA 311",
      "area": "SPA",
      "type": "XUAT",
      "quantity": 1,
      "note": "KIỆT MUA",
      "date": "2025-11-14",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-14T08:02:01",
      "timestamp": "2025-11-14T08:02:01"
    },
    {
      "id": "inv-import-kho-45-xuat-51",
      "itemName": "DẦU HOA 311",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "KIỆT MUA",
      "date": "2025-11-14",
      "transferId": "invtf-import-0023",
      "transferRole": "OUT",
      "transferCounterpartyArea": "SPA",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-14T08:00:51",
      "timestamp": "2025-11-14T08:00:51"
    },
    {
      "id": "inv-import-spa-15-xuat-120",
      "itemName": "DẦU HOA 311",
      "area": "SPA",
      "type": "XUAT",
      "quantity": 3,
      "note": "BÁN (CK 5%)",
      "date": "2025-11-12",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-12T08:02:00",
      "timestamp": "2025-11-12T08:02:00"
    },
    {
      "id": "inv-import-spa-12-xuat-116",
      "itemName": "DẦU HOA 202",
      "area": "SPA",
      "type": "XUAT",
      "quantity": 2,
      "note": "BÁN (CK 5%)",
      "date": "2025-11-12",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-12T08:01:56",
      "timestamp": "2025-11-12T08:01:56"
    },
    {
      "id": "inv-import-kho-44-xuat-50",
      "itemName": "DẦU HOA 311",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 3,
      "note": "BÁN (CK 5%)",
      "date": "2025-11-12",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-12T08:00:50",
      "timestamp": "2025-11-12T08:00:50"
    },
    {
      "id": "inv-import-kho-43-xuat-49",
      "itemName": "DẦU HOA 202",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 2,
      "note": "BÁN (CK 5%)",
      "date": "2025-11-12",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-12T08:00:49",
      "timestamp": "2025-11-12T08:00:49"
    },
    {
      "id": "inv-import-spa-32-nhap-138",
      "itemName": "MÁY THỔI  VITALITY WAND",
      "area": "SPA",
      "type": "NHAP",
      "quantity": 1,
      "note": "phòng cộng đồng (thay thế 1 máy trả hàng Seri HF02050400243E)",
      "date": "2025-11-11",
      "transferId": "invtf-import-0008",
      "transferRole": "IN",
      "transferCounterpartyArea": "KHO",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-11T08:02:18",
      "timestamp": "2025-11-11T08:02:18"
    },
    {
      "id": "inv-import-spa-7-nhap-111",
      "itemName": "DẦU BABY OIL",
      "area": "SPA",
      "type": "NHAP",
      "quantity": 2,
      "note": "DỊCH VỤ SPA",
      "date": "2025-11-11",
      "transferId": "invtf-import-0009",
      "transferRole": "IN",
      "transferCounterpartyArea": "KHO",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-11T08:01:51",
      "timestamp": "2025-11-11T08:01:51"
    },
    {
      "id": "inv-import-kho-42-xuat-48",
      "itemName": "MÁY THỔI  VITALITY WAND",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "phòng cộng đồng (thay thế 1 máy trả hàng Seri HF02050400243E)",
      "date": "2025-11-11",
      "transferId": "invtf-import-0008",
      "transferRole": "OUT",
      "transferCounterpartyArea": "SPA",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-11T08:00:48",
      "timestamp": "2025-11-11T08:00:48"
    },
    {
      "id": "inv-import-kho-41-xuat-47",
      "itemName": "DẦU BABY OIL",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 2,
      "note": "DỊCH VỤ SPA",
      "date": "2025-11-11",
      "transferId": "invtf-import-0009",
      "transferRole": "OUT",
      "transferCounterpartyArea": "SPA",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-11T08:00:47",
      "timestamp": "2025-11-11T08:00:47"
    },
    {
      "id": "inv-import-kho-41-nhap-46",
      "itemName": "DẦU BABY OIL",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 2,
      "note": "DỊCH VỤ SPA",
      "date": "2025-11-11",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-11T08:00:46",
      "timestamp": "2025-11-11T08:00:46"
    },
    {
      "id": "inv-import-spa-3-xuat-107",
      "itemName": "BĂNG VỆ SINH",
      "area": "SPA",
      "type": "XUAT",
      "quantity": 1,
      "note": "SUNNY (1 THÙNG)",
      "date": "2025-11-10",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-10T08:01:47",
      "timestamp": "2025-11-10T08:01:47"
    },
    {
      "id": "inv-import-kho-40-xuat-45",
      "itemName": "BĂNG VỆ SINH",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "SUNNY (1 THÙNG)",
      "date": "2025-11-10",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-10T08:00:45",
      "timestamp": "2025-11-10T08:00:45"
    },
    {
      "id": "inv-import-spa-41-xuat-147",
      "itemName": "TERA P90",
      "area": "SPA",
      "type": "XUAT",
      "quantity": 3,
      "note": "CƯỜNG TRẢ CDUNG",
      "date": "2025-11-06",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-06T08:02:27",
      "timestamp": "2025-11-06T08:02:27"
    },
    {
      "id": "inv-import-spa-30-xuat-136",
      "itemName": "MÁY NƯỚC H+",
      "area": "SPA",
      "type": "XUAT",
      "quantity": 1,
      "note": "Sunny lấy",
      "date": "2025-11-06",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-06T08:02:16",
      "timestamp": "2025-11-06T08:02:16"
    },
    {
      "id": "inv-import-kho-39-xuat-44",
      "itemName": "TERA P90",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 3,
      "note": "CƯỜNG TRẢ CDUNG",
      "date": "2025-11-06",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-06T08:00:44",
      "timestamp": "2025-11-06T08:00:44"
    },
    {
      "id": "inv-import-kho-38-nhap-43",
      "itemName": "MÁY THỔI  VITALITY WAND",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 3,
      "note": "",
      "date": "2025-11-06",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-06T08:00:43",
      "timestamp": "2025-11-06T08:00:43"
    },
    {
      "id": "inv-import-kho-37-xuat-42",
      "itemName": "MÁY NƯỚC H+",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "Sunny lấy",
      "date": "2025-11-06",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-06T08:00:42",
      "timestamp": "2025-11-06T08:00:42"
    },
    {
      "id": "inv-import-kho-37-nhap-41",
      "itemName": "MÁY NƯỚC H+",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 2,
      "note": "Sunny lấy",
      "date": "2025-11-06",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-06T08:00:41",
      "timestamp": "2025-11-06T08:00:41"
    },
    {
      "id": "inv-import-kho-36-nhap-40",
      "itemName": "GEL XANH",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 17,
      "note": "",
      "date": "2025-11-06",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-06T08:00:40",
      "timestamp": "2025-11-06T08:00:40"
    },
    {
      "id": "inv-import-kho-35-nhap-39",
      "itemName": "GEL NÂU",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 17,
      "note": "",
      "date": "2025-11-06",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-06T08:00:39",
      "timestamp": "2025-11-06T08:00:39"
    },
    {
      "id": "inv-import-kho-34-nhap-38",
      "itemName": "CC DRINK",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 2,
      "note": "",
      "date": "2025-11-06",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-06T08:00:38",
      "timestamp": "2025-11-06T08:00:38"
    },
    {
      "id": "inv-import-kho-33-nhap-37",
      "itemName": "BVS NGÀY NHIỀU 15M",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 10,
      "note": "HỘP",
      "date": "2025-11-06",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-06T08:00:37",
      "timestamp": "2025-11-06T08:00:37"
    },
    {
      "id": "inv-import-kho-32-nhap-36",
      "itemName": "BVS NGÀY 16M",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 30,
      "note": "HỘP",
      "date": "2025-11-06",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-06T08:00:36",
      "timestamp": "2025-11-06T08:00:36"
    },
    {
      "id": "inv-import-kho-31-nhap-35",
      "itemName": "BVS HÀNG NGÀY 30M",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 10,
      "note": "HỘP",
      "date": "2025-11-06",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-06T08:00:35",
      "timestamp": "2025-11-06T08:00:35"
    },
    {
      "id": "inv-import-kho-30-nhap-34",
      "itemName": "BVS ĐÊM 15M",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 10,
      "note": "HỘP",
      "date": "2025-11-06",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-06T08:00:34",
      "timestamp": "2025-11-06T08:00:34"
    },
    {
      "id": "inv-import-kho-29-nhap-33",
      "itemName": "BĂNG VỆ SINH",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 10,
      "note": "10 THÙNG NHỎ 6 HỘP 4 LOẠI/ THÙNG(1 HÀNG NGÀY 30M/H, 3 NGÀY 16M/H, 1 NGÀY NHIỀU 15M/H,1 ĐÊM 15M/H)",
      "date": "2025-11-06",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-06T08:00:33",
      "timestamp": "2025-11-06T08:00:33"
    },
    {
      "id": "inv-import-spa-6-nhap-110",
      "itemName": "CC DRINK",
      "area": "SPA",
      "type": "NHAP",
      "quantity": 1,
      "note": "TRƯNG BÀY P6",
      "date": "2025-11-03",
      "transferId": "invtf-import-0010",
      "transferRole": "IN",
      "transferCounterpartyArea": "KHO",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-03T08:01:50",
      "timestamp": "2025-11-03T08:01:50"
    },
    {
      "id": "inv-import-kho-28-xuat-32",
      "itemName": "CC DRINK",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "TRƯNG BÀY P6",
      "date": "2025-11-03",
      "transferId": "invtf-import-0010",
      "transferRole": "OUT",
      "transferCounterpartyArea": "SPA",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-03T08:00:32",
      "timestamp": "2025-11-03T08:00:32"
    },
    {
      "id": "inv-import-spa-38-nhap-144",
      "itemName": "SÁP GIỮ ẤM C3",
      "area": "SPA",
      "type": "NHAP",
      "quantity": 1,
      "note": "DỊCH VỤ SPA",
      "date": "2025-11-02",
      "transferId": "invtf-import-0011",
      "transferRole": "IN",
      "transferCounterpartyArea": "KHO",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-02T08:02:24",
      "timestamp": "2025-11-02T08:02:24"
    },
    {
      "id": "inv-import-spa-14-xuat-119",
      "itemName": "DẦU HOA 311",
      "area": "SPA",
      "type": "XUAT",
      "quantity": 4,
      "note": "4 BÁN,1 DỊCH VỤ SPA",
      "date": "2025-11-02",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-02T08:01:59",
      "timestamp": "2025-11-02T08:01:59"
    },
    {
      "id": "inv-import-spa-14-nhap-118",
      "itemName": "DẦU HOA 311",
      "area": "SPA",
      "type": "NHAP",
      "quantity": 1,
      "note": "4 BÁN,1 DỊCH VỤ SPA",
      "date": "2025-11-02",
      "transferId": "invtf-import-0023",
      "transferRole": "IN",
      "transferCounterpartyArea": "KHO",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-02T08:01:58",
      "timestamp": "2025-11-02T08:01:58"
    },
    {
      "id": "inv-import-spa-11-xuat-115",
      "itemName": "DẦU HOA 202",
      "area": "SPA",
      "type": "XUAT",
      "quantity": 1,
      "note": "BÁN",
      "date": "2025-11-02",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-02T08:01:55",
      "timestamp": "2025-11-02T08:01:55"
    },
    {
      "id": "inv-import-kho-27-xuat-31",
      "itemName": "SÁP GIỮ ẤM C3",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "DỊCH VỤ SPA",
      "date": "2025-11-02",
      "transferId": "invtf-import-0011",
      "transferRole": "OUT",
      "transferCounterpartyArea": "SPA",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-02T08:00:31",
      "timestamp": "2025-11-02T08:00:31"
    },
    {
      "id": "inv-import-kho-26-xuat-30",
      "itemName": "DẦU HOA 311",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 5,
      "note": "4 BÁN,1 DỊCH VỤ SPA",
      "date": "2025-11-02",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-02T08:00:30",
      "timestamp": "2025-11-02T08:00:30"
    },
    {
      "id": "inv-import-kho-25-xuat-29",
      "itemName": "DẦU HOA 202",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "BÁN",
      "date": "2025-11-02",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-02T08:00:29",
      "timestamp": "2025-11-02T08:00:29"
    },
    {
      "id": "inv-import-spa-10-nhap-114",
      "itemName": "DẦU HOA 202",
      "area": "SPA",
      "type": "NHAP",
      "quantity": 1,
      "note": "DỊCH VỤ SPA",
      "date": "2025-11-01",
      "transferId": "invtf-import-0012",
      "transferRole": "IN",
      "transferCounterpartyArea": "KHO",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-01T08:01:54",
      "timestamp": "2025-11-01T08:01:54"
    },
    {
      "id": "inv-import-spa-8-nhap-112",
      "itemName": "DẦU GỘI THẢO DƯỢC",
      "area": "SPA",
      "type": "NHAP",
      "quantity": 1,
      "note": "SPA",
      "date": "2025-11-01",
      "transferId": "invtf-import-0013",
      "transferRole": "IN",
      "transferCounterpartyArea": "KHO",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-01T08:01:52",
      "timestamp": "2025-11-01T08:01:52"
    },
    {
      "id": "inv-import-kho-24-nhap-28",
      "itemName": "SÁP GIỮ ẤM C3",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 1,
      "note": "",
      "date": "2025-11-01",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-01T08:00:28",
      "timestamp": "2025-11-01T08:00:28"
    },
    {
      "id": "inv-import-kho-23-nhap-27",
      "itemName": "SÁP GIỮ ẤM  C4",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 1,
      "note": "",
      "date": "2025-11-01",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-01T08:00:27",
      "timestamp": "2025-11-01T08:00:27"
    },
    {
      "id": "inv-import-kho-22-nhap-26",
      "itemName": "DẦU HOA 311",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 12,
      "note": "",
      "date": "2025-11-01",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-01T08:00:26",
      "timestamp": "2025-11-01T08:00:26"
    },
    {
      "id": "inv-import-kho-21-nhap-25",
      "itemName": "DẦU HOA 202",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 5,
      "note": "",
      "date": "2025-11-01",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-01T08:00:25",
      "timestamp": "2025-11-01T08:00:25"
    },
    {
      "id": "inv-import-kho-20-xuat-24",
      "itemName": "DẦU HOA 202",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "DỊCH VỤ SPA",
      "date": "2025-11-01",
      "transferId": "invtf-import-0012",
      "transferRole": "OUT",
      "transferCounterpartyArea": "SPA",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-01T08:00:24",
      "timestamp": "2025-11-01T08:00:24"
    },
    {
      "id": "inv-import-kho-19-xuat-23",
      "itemName": "DẦU GỘI THẢO DƯỢC",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "SPA",
      "date": "2025-11-01",
      "transferId": "invtf-import-0013",
      "transferRole": "OUT",
      "transferCounterpartyArea": "SPA",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-01T08:00:23",
      "timestamp": "2025-11-01T08:00:23"
    },
    {
      "id": "inv-import-kho-19-nhap-22",
      "itemName": "DẦU GỘI THẢO DƯỢC",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 1,
      "note": "SPA",
      "date": "2025-11-01",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-11-01T08:00:22",
      "timestamp": "2025-11-01T08:00:22"
    },
    {
      "id": "inv-import-kho-18-nhap-21",
      "itemName": "TERA P90 Plus",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 4,
      "note": "",
      "date": "2025-10-31",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-10-31T08:00:21",
      "timestamp": "2025-10-31T08:00:21"
    },
    {
      "id": "inv-import-kho-17-nhap-20",
      "itemName": "MÁY THỔI  VITALITY WAND",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 2,
      "note": "",
      "date": "2025-10-31",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-10-31T08:00:20",
      "timestamp": "2025-10-31T08:00:20"
    },
    {
      "id": "inv-import-kho-16-nhap-19",
      "itemName": "GEL XANH",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 14,
      "note": "",
      "date": "2025-10-31",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-10-31T08:00:19",
      "timestamp": "2025-10-31T08:00:19"
    },
    {
      "id": "inv-import-kho-15-nhap-18",
      "itemName": "GEL NÂU",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 14,
      "note": "",
      "date": "2025-10-31",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-10-31T08:00:18",
      "timestamp": "2025-10-31T08:00:18"
    },
    {
      "id": "inv-import-kho-14-nhap-17",
      "itemName": "CC DRINK",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 10,
      "note": "",
      "date": "2025-10-31",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-10-31T08:00:17",
      "timestamp": "2025-10-31T08:00:17"
    },
    {
      "id": "inv-import-spa-42-nhap-148",
      "itemName": "TERA P90 Plus",
      "area": "SPA",
      "type": "NHAP",
      "quantity": 1,
      "note": "DỊCH VỤ SPA",
      "date": "2025-10-27",
      "transferId": "invtf-import-0014",
      "transferRole": "IN",
      "transferCounterpartyArea": "KHO",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-10-27T08:02:28",
      "timestamp": "2025-10-27T08:02:28"
    },
    {
      "id": "inv-import-kho-13-xuat-16",
      "itemName": "TERA P90 Plus",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "DỊCH VỤ SPA",
      "date": "2025-10-27",
      "transferId": "invtf-import-0014",
      "transferRole": "OUT",
      "transferCounterpartyArea": "SPA",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-10-27T08:00:16",
      "timestamp": "2025-10-27T08:00:16"
    },
    {
      "id": "inv-import-kho-11-nhap-15",
      "itemName": "TERA P90 Plus",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 2,
      "note": "",
      "date": "2025-10-26",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-10-26T08:00:15",
      "timestamp": "2025-10-26T08:00:15"
    },
    {
      "id": "inv-import-kho-10-nhap-14",
      "itemName": "TERA P90",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 6,
      "note": "",
      "date": "2025-10-26",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-10-26T08:00:14",
      "timestamp": "2025-10-26T08:00:14"
    },
    {
      "id": "inv-import-kho-9-nhap-13",
      "itemName": "MÁY THỔI  VITALITY WAND",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 2,
      "note": "",
      "date": "2025-10-26",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-10-26T08:00:13",
      "timestamp": "2025-10-26T08:00:13"
    },
    {
      "id": "inv-import-spa-40-nhap-146",
      "itemName": "TERA P90",
      "area": "SPA",
      "type": "NHAP",
      "quantity": 2,
      "note": "P6",
      "date": "2025-10-15",
      "transferId": "invtf-import-0015",
      "transferRole": "IN",
      "transferCounterpartyArea": "KHO",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-10-15T08:02:26",
      "timestamp": "2025-10-15T08:02:26"
    },
    {
      "id": "inv-import-spa-31-nhap-137",
      "itemName": "MÁY THỔI  VITALITY WAND",
      "area": "SPA",
      "type": "NHAP",
      "quantity": 1,
      "note": "P6",
      "date": "2025-10-15",
      "transferId": "invtf-import-0016",
      "transferRole": "IN",
      "transferCounterpartyArea": "KHO",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-10-15T08:02:17",
      "timestamp": "2025-10-15T08:02:17"
    },
    {
      "id": "inv-import-spa-28-nhap-134",
      "itemName": "MÁY MẮT",
      "area": "SPA",
      "type": "NHAP",
      "quantity": 1,
      "note": "P6",
      "date": "2025-10-15",
      "transferId": "invtf-import-0017",
      "transferRole": "IN",
      "transferCounterpartyArea": "KHO",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-10-15T08:02:14",
      "timestamp": "2025-10-15T08:02:14"
    },
    {
      "id": "inv-import-spa-20-nhap-125",
      "itemName": "GEL XANH",
      "area": "SPA",
      "type": "NHAP",
      "quantity": 1,
      "note": "P6",
      "date": "2025-10-15",
      "transferId": "invtf-import-0018",
      "transferRole": "IN",
      "transferCounterpartyArea": "KHO",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-10-15T08:02:05",
      "timestamp": "2025-10-15T08:02:05"
    },
    {
      "id": "inv-import-spa-18-nhap-123",
      "itemName": "GEL NÂU",
      "area": "SPA",
      "type": "NHAP",
      "quantity": 1,
      "note": "P6",
      "date": "2025-10-15",
      "transferId": "invtf-import-0019",
      "transferRole": "IN",
      "transferCounterpartyArea": "KHO",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-10-15T08:02:03",
      "timestamp": "2025-10-15T08:02:03"
    },
    {
      "id": "inv-import-kho-8-xuat-12",
      "itemName": "TERA P90 Plus",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "P6 (đưa chú Vĩ ngày 28/11)",
      "date": "2025-10-15",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-10-15T08:00:12",
      "timestamp": "2025-10-15T08:00:12"
    },
    {
      "id": "inv-import-kho-8-nhap-11",
      "itemName": "TERA P90 Plus",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 1,
      "note": "P6 (đưa chú Vĩ ngày 28/11)",
      "date": "2025-10-15",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-10-15T08:00:11",
      "timestamp": "2025-10-15T08:00:11"
    },
    {
      "id": "inv-import-kho-7-xuat-10",
      "itemName": "TERA P90",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 2,
      "note": "P6",
      "date": "2025-10-15",
      "transferId": "invtf-import-0015",
      "transferRole": "OUT",
      "transferCounterpartyArea": "SPA",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-10-15T08:00:10",
      "timestamp": "2025-10-15T08:00:10"
    },
    {
      "id": "inv-import-kho-7-nhap-9",
      "itemName": "TERA P90",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 4,
      "note": "P6",
      "date": "2025-10-15",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-10-15T08:00:09",
      "timestamp": "2025-10-15T08:00:09"
    },
    {
      "id": "inv-import-kho-6-xuat-8",
      "itemName": "MÁY THỔI  VITALITY WAND",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "P6( đưa chú Vĩ ngày 28/11)",
      "date": "2025-10-15",
      "transferId": "invtf-import-0016",
      "transferRole": "OUT",
      "transferCounterpartyArea": "SPA",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-10-15T08:00:08",
      "timestamp": "2025-10-15T08:00:08"
    },
    {
      "id": "inv-import-kho-6-nhap-7",
      "itemName": "MÁY THỔI  VITALITY WAND",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 1,
      "note": "P6( đưa chú Vĩ ngày 28/11)",
      "date": "2025-10-15",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-10-15T08:00:07",
      "timestamp": "2025-10-15T08:00:07"
    },
    {
      "id": "inv-import-kho-5-xuat-6",
      "itemName": "MÁY MẮT",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "P6",
      "date": "2025-10-15",
      "transferId": "invtf-import-0017",
      "transferRole": "OUT",
      "transferCounterpartyArea": "SPA",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-10-15T08:00:06",
      "timestamp": "2025-10-15T08:00:06"
    },
    {
      "id": "inv-import-kho-5-nhap-5",
      "itemName": "MÁY MẮT",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 1,
      "note": "P6",
      "date": "2025-10-15",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-10-15T08:00:05",
      "timestamp": "2025-10-15T08:00:05"
    },
    {
      "id": "inv-import-kho-4-xuat-4",
      "itemName": "GEL XANH",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "P6",
      "date": "2025-10-15",
      "transferId": "invtf-import-0018",
      "transferRole": "OUT",
      "transferCounterpartyArea": "SPA",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-10-15T08:00:04",
      "timestamp": "2025-10-15T08:00:04"
    },
    {
      "id": "inv-import-kho-4-nhap-3",
      "itemName": "GEL XANH",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 1,
      "note": "P6",
      "date": "2025-10-15",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-10-15T08:00:03",
      "timestamp": "2025-10-15T08:00:03"
    },
    {
      "id": "inv-import-kho-3-xuat-2",
      "itemName": "GEL NÂU",
      "area": "KHO",
      "type": "XUAT",
      "quantity": 1,
      "note": "P6",
      "date": "2025-10-15",
      "transferId": "invtf-import-0019",
      "transferRole": "OUT",
      "transferCounterpartyArea": "SPA",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-10-15T08:00:02",
      "timestamp": "2025-10-15T08:00:02"
    },
    {
      "id": "inv-import-kho-3-nhap-1",
      "itemName": "GEL NÂU",
      "area": "KHO",
      "type": "NHAP",
      "quantity": 1,
      "note": "P6",
      "date": "2025-10-15",
      "transferId": "",
      "transferRole": "",
      "transferCounterpartyArea": "",
      "createdBy": "user-admin-default",
      "created_by": "user-admin-default",
      "createdAt": "2025-10-15T08:00:01",
      "timestamp": "2025-10-15T08:00:01"
    }
  ]
};
